#!/usr/bin/env python

import os
import torch
import numpy as np
import cv2
import rospy
from cv_bridge import CvBridge
from grid_map_msgs.msg import GridMap
from monoforce.config import Config
from monoforce.models import RigidBodySoftTerrain, State
from monoforce.models.monolayout import load_monodem
from monoforce.ros import height_map_to_point_cloud_msg, height_map_to_gridmap_msg, to_marker, to_path
from monoforce.utils import normalize
from nav_msgs.msg import Path
from ros_numpy import numpify
from sensor_msgs.msg import Image, CompressedImage, PointCloud2
import rospkg
from time import time
from scipy.ndimage import rotate
from visualization_msgs.msg import MarkerArray


pkg_path = rospkg.RosPack().get_path('monoforce')

class DiffPhysics:
    def __init__(self, cfg: Config,
                 hm_topic='/height_map',
                 hm_frame='base_link',
                 linear_vels=[1.],
                 angular_vels=[0.]):
        self.cfg = cfg
        self.hm_frame = hm_frame
        self.linear_vels = linear_vels
        self.angular_vels = angular_vels

        # paths publisher
        self.paths_pub = rospy.Publisher('/sampled_paths', MarkerArray, queue_size=1)
        # lower cost path publisher
        self.lc_path_pub = rospy.Publisher('/lower_cost_path', Path, queue_size=1)

        # image subscriber
        self.hm_sub = rospy.Subscriber(hm_topic, PointCloud2, self.hm_callback)

    def hm_callback(self, msg):
        assert isinstance(msg, PointCloud2)
        # if message is stale do not process it
        dt = rospy.Time.now() - msg.header.stamp
        if dt > rospy.Duration(2.):
            rospy.logdebug(f'Stale height map message received ({dt.to_sec():.1f} [sec]), skipping')
            return

        height = numpify(msg)['z']
        h = w = int(self.cfg.d_max / self.cfg.grid_res)
        height = height.reshape((h, w))
        height = np.asarray(height, dtype=np.float64)
        height = height.T
        rospy.loginfo('Received height map of shape: %s' % str(height.shape))

        # predict path
        with torch.no_grad():
            self.predict_paths(height, linear_vels=self.linear_vels, angular_vels=self.angular_vels)

    def sim(self, height, controls):
        assert isinstance(height, np.ndarray)
        assert height.shape[0] == height.shape[1]
        assert isinstance(controls, dict)
        assert 'stamps' in controls.keys()
        assert 'linear_v' in controls.keys()
        assert 'angular_w' in controls.keys()

        h, w = np.asarray(height.shape) * self.cfg.grid_res
        state = State(xyz=torch.tensor([0, 0., 0.], device=self.cfg.device).view(3, 1),
                   rot=torch.eye(3, device=self.cfg.device),
                   vel=torch.tensor([0., 0., 0.], device=self.cfg.device).view(3, 1),
                   omega=torch.tensor([0., 0., 0.], device=self.cfg.device).view(3, 1),
                   device=self.cfg.device)
        state[0][0] = -h / 2.  # move robot to the edge of the height map

        """ Create robot-terrain interaction models """
        system = RigidBodySoftTerrain(height=height,
                                      grid_res=self.cfg.grid_res,
                                      friction=self.cfg.friction,
                                      mass=self.cfg.robot_mass,
                                      state=state,
                                      device=self.cfg.device, use_ode=False,
                                      interaction_model='diffdrive')

        # put models with their params to self.cfg.device
        system = system.to(self.cfg.device)
        tt = controls['stamps'].to(self.cfg.device)

        """ Navigation loop """
        dt = (tt[1:] - tt[:-1]).mean()

        xyz, Rs, linear_v, angular_w, forces = state
        xyz, Rs, linear_v, angular_w, forces = [xyz], [Rs], [linear_v], [angular_w], [forces]

        for t in range(len(tt[1:])):
            v, w = controls['linear_v'][t], controls['angular_w'][t]

            state[2][0] = v
            state[3][2] = w

            dstate = system.forward(t, state)
            state = state.update(dstate, dt)

            xyz.append(state[0])
            Rs.append(state[1])
            linear_v.append(state[2])
            angular_w.append(state[3])
            forces.append(state[4])

        # height map origin is at the edge of the map
        xyz = torch.stack(xyz) + torch.tensor([h / 2., 0., 0.], device=self.cfg.device).view(3, 1)
        Rs = torch.stack(Rs)
        linear_v = torch.stack(linear_v)
        angular_w = torch.stack(angular_w)
        forces = torch.stack(forces)

        states = [xyz, Rs, linear_v, angular_w, forces]

        return states

    def path_cost(self, states):
        assert isinstance(states, list)
        assert len(states) == 5
        xyz, Rs, linear_v, angular_w, forces = states
        # path cost as a sum of force magnitudes
        assert forces.ndim == 3  # (n_samples, 3, n_points)
        # reduce forces acting on all robot points
        forces = forces.sum(dim=2)
        assert forces.shape[1] == 3
        cost = forces.norm(dim=1).mean()
        return cost

    def predict_paths(self, height, linear_vels=None, angular_vels=None):
        if angular_vels is None:
            angular_vels = [0.]
        if linear_vels is None:
            linear_vels = [1.]
        assert isinstance(height, np.ndarray)

        tt = torch.linspace(0., self.cfg.total_sim_time, self.cfg.n_samples)
        # paths marker array
        marker_array = MarkerArray()
        path_id = 0
        lower_cost_poses = None
        max_path_cost = torch.tensor(-np.inf, device=self.cfg.device)
        min_path_cost = torch.tensor(np.inf, device=self.cfg.device)
        for v in linear_vels:
            for w in angular_vels:
                # controls
                controls = {
                    'stamps': tt,
                    'linear_v': v * torch.ones(self.cfg.n_samples),
                    'angular_w': w * torch.ones(self.cfg.n_samples)
                }

                # predict states
                t0 = time()
                states = self.sim(height, controls)
                t1 = time()
                rospy.logdebug('Path of %d samples simulation took %.3f' % (self.cfg.n_samples, t1 - t0))

                # create path message (Marker)
                xyz = states[0].cpu().numpy()[::100]
                Rs = states[1].cpu().numpy()[::100]
                Ts = np.zeros((len(xyz), 4, 4))
                Ts[:, :3, :3] = Rs
                Ts[:, :3, 3:4] = xyz
                Ts[:, 3, 3] = 1.

                # compute path cost
                path_cost = self.path_cost(states)
                # rospy.logdebug('Path cost: %.3f' % path_cost.item())
                if path_cost > max_path_cost:
                    max_path_cost = path_cost.clone()
                if path_cost < min_path_cost:
                    min_path_cost = path_cost.clone()
                    lower_cost_poses = Ts
                # normalize path cost
                path_cost = (path_cost - min_path_cost) / (max_path_cost - min_path_cost) if max_path_cost > min_path_cost else path_cost
                # rospy.logdebug('Path cost normalized: %.3f' % path_cost.item())

                # map path cost to color (lower cost -> greener, higher cost -> redder)
                color = np.array([0., 1., 0.]) + (np.array([1., 0., 0.]) - np.array([0., 1., 0.])) * path_cost.item()
                marker_msg = to_marker(Ts, color=color)
                marker_msg.header.stamp = rospy.Time.now()
                marker_msg.header.frame_id = self.hm_frame
                marker_msg.ns = 'paths'
                marker_msg.id = path_id
                path_id += 1
                marker_array.markers.append(marker_msg)
                rospy.logdebug('Path to marker array conversion took %.3f' % (time() - t1))

        # publish all sampled paths
        self.paths_pub.publish(marker_array)
        # publish lower cost path
        if lower_cost_poses is not None:
            path_msg = to_path(lower_cost_poses, stamp=rospy.Time.now(), frame_id=self.hm_frame)
            path_msg.header.stamp = rospy.Time.now()
            path_msg.header.frame_id = self.hm_frame
            self.lc_path_pub.publish(path_msg)


def main():
    rospy.init_node('diff_physics', anonymous=True, log_level=rospy.DEBUG)

    cfg = Config()
    cfg.grid_res = 0.1
    cfg.device = 'cuda'
    cfg.d_max = 12.8
    cfg.d_min = 1.
    cfg.total_sim_time = rospy.get_param('~total_sim_time', 5.)
    cfg.n_samples = 100 * int(cfg.total_sim_time)

    hm_topic = rospy.get_param('~hm_topic')
    hm_frame = rospy.get_param('~hm_frame')
    # control parameters
    linear_vels = rospy.get_param('~linear_vels', [1.])
    angular_vels = rospy.get_param('~angular_vels', [0.])
    try:
        node = DiffPhysics(cfg=cfg, hm_topic=hm_topic, hm_frame=hm_frame,
                           linear_vels=linear_vels, angular_vels=angular_vels)
        rospy.spin()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
