#!/usr/bin/env python

import rosbag
from tqdm import tqdm


input_bag = '/home/ruslan/data/bags/husky_sim/depth/husky_simcity_2024-01-16-11-23-56_depth.bag'
output_bag = input_bag[:-4] + '_synch.bag'

with rosbag.Bag(output_bag, 'w') as outbag:
    for topic, msg, t in tqdm(rosbag.Bag(input_bag).read_messages(), total=rosbag.Bag(input_bag).get_message_count()):
        # This also replaces tf timestamps under the assumption 
        # that all transforms in the message share the same timestamp
        if topic == "/tf" and msg.transforms:
            outbag.write(topic, msg, msg.transforms[0].header.stamp)
        else:
            outbag.write(topic, msg, msg.header.stamp if msg._has_header else t)
