#!/usr/bin/env python

from rosbag import Compression, Bag
from tqdm import tqdm
from monoforce.datasets import robingas_husky_seq_paths, sim_seq_paths

paths = robingas_husky_seq_paths + sim_seq_paths

for path in paths:
    input_bag_path = path.replace('_trav', '.bag')
    print('Processing', input_bag_path)
    output_bag_path = input_bag_path[:-4] + '_synch.bag'
    print('Saving to', output_bag_path)

    input_bag = Bag(input_bag_path)
    with Bag(output_bag_path, 'w', compression=Compression.LZ4) as output_bag:
        for topic, msg, t in tqdm(input_bag.read_messages(), total=input_bag.get_message_count()):
            # This also replaces tf timestamps under the assumption
            # that all transforms in the message share the same timestamp
            if topic == "/tf" and msg.transforms:
                output_bag.write(topic, msg, msg.transforms[0].header.stamp)
            else:
                output_bag.write(topic, msg, msg.header.stamp if msg._has_header else t)
