#!/usr/bin/env python

import os
import torch
import numpy as np
from torch.utils.data import ConcatDataset
from monoforce.models.lss.model import compile_model
from monoforce.datasets.data import OmniDemData, explore_data
from monoforce.config import Config
from monoforce.datasets import seq_paths
from monoforce.models.lss.tools import MSELoss
from tqdm import tqdm


torch.set_default_dtype(torch.float32)


def create_datasets(train_paths, val_path, data_aug_conf, grid_conf, cfg, debug=False, vis=False):
    # create dataset for LSS model training
    datasets = []
    print('Train paths:', train_paths)
    print('Val path:', val_path)
    for path in train_paths:
        assert os.path.exists(path)
        train_ds = OmniDemData(path, is_train=True, data_aug_conf=data_aug_conf, cfg=cfg)
        if vis:
            explore_data(path, grid_conf, data_aug_conf, cfg, save=False)
        datasets.append(train_ds)
    train_ds = ConcatDataset(datasets)

    # create validation dataset
    val_ds = OmniDemData(val_path, is_train=False, data_aug_conf=data_aug_conf, cfg=cfg)
    if vis:
        explore_data(val_path, grid_conf, data_aug_conf, cfg, save=False)

    if debug:
        print('Debug mode: using small datasets')
        train_ds = torch.utils.data.Subset(train_ds, np.random.choice(len(train_ds), 32, replace=False))
        val_ds = torch.utils.data.Subset(val_ds, np.random.choice(len(val_ds), 16, replace=False))
    print('Training dataset size:', len(train_ds))
    print('Validation dataset size:', len(val_ds))

    return train_ds, val_ds


def main():
    cfg = Config()
    cfg.d_min = 0.6
    cfg.d_max = 6.4
    cfg.grid_res = 0.1
    cfg.h_max = 1.0
    cfg.device = torch.device('cuda:0')
    cfg.lr = 1e-3
    cfg.weight_decay = 1e-7

    max_grad_norm = 5.0
    bsz = 4
    nworkers = 10
    nepochs = 100

    grid_conf = {
        'xbound': [-cfg.d_max, cfg.d_max, cfg.grid_res],
        'ybound': [-cfg.d_max, cfg.d_max, cfg.grid_res],
        'zbound': [-10.0, 10.0, 20.0],
        'dbound': [cfg.d_min, cfg.d_max, cfg.grid_res],
    }

    data_aug_conf = {
                    'resize_lim': (0.193, 0.225),
                    'final_dim': (128, 352),
                    'rot_lim': (-5.4, 5.4),
                    'H': 1200, 'W': 1920,
                    'rand_flip': False,
                    'bot_pct_lim': (0.0, 0.22),
                    'cams': ['CAM_FRONT', 'CAM_REAR', 'CAM_RIGHT', 'CAM_LEFT'],
                    'Ncams': 4,
                }

    train_ds_paths = seq_paths[:-1]
    val_ds_path = seq_paths[-1]

    train_ds, val_ds = create_datasets(train_ds_paths, val_ds_path,
                                       data_aug_conf=data_aug_conf, grid_conf=grid_conf, cfg=cfg,
                                       vis=False, debug=False)
    trainloader = torch.utils.data.DataLoader(train_ds, batch_size=bsz, shuffle=True, num_workers=nworkers)
    valloader = torch.utils.data.DataLoader(val_ds, batch_size=bsz, shuffle=False, num_workers=nworkers)

    model = compile_model(grid_conf, data_aug_conf, outC=1)
    model.to(cfg.device)

    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    loss_fn = MSELoss()

    min_loss = np.inf
    min_train_loss = np.inf
    for epoch in range(nepochs):
        # training epoch
        model.train()
        train_loss = 0.0
        for batchi, (imgs, rots, trans, intrins, post_rots, post_trans, heightmap)\
                in tqdm(enumerate(trainloader), total=len(trainloader)):
            optimizer.zero_grad()

            inputs = [imgs, rots, trans, intrins, post_rots, post_trans]
            inputs = [torch.as_tensor(i, dtype=torch.float32) for i in inputs]
            inputs = [i.to(cfg.device) for i in inputs]
            preds = model(*inputs)

            heightmap = torch.as_tensor(heightmap, dtype=torch.float32)
            heightmap = heightmap.to(cfg.device)

            loss = loss_fn(preds, heightmap)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(trainloader)
        print('Training loss:', train_loss)
        if train_loss < min_train_loss:
            min_train_loss = train_loss
            print('Saving train model...')
            torch.save(model.state_dict(), f'train_lss.pt')

        # validation epoch
        with torch.no_grad():
            model.eval()
            val_loss = 0.0
            for batchi, (imgs, rots, trans, intrins, post_rots, post_trans, heightmap)\
                    in tqdm(enumerate(valloader), total=len(valloader)):
                inputs = [imgs, rots, trans, intrins, post_rots, post_trans]
                inputs = [torch.as_tensor(i, dtype=torch.float32) for i in inputs]
                inputs = [i.to(cfg.device) for i in inputs]
                preds = model(*inputs)

                heightmap = torch.as_tensor(heightmap, dtype=torch.float32)
                heightmap = heightmap.to(cfg.device)

                loss = loss_fn(preds, heightmap)
                val_loss += loss.item()
            val_loss /= len(valloader)
            print('Validation loss:', val_loss)

            if val_loss < min_loss:
                min_loss = val_loss
                print('Saving model...')
                torch.save(model.state_dict(), 'lss.pt')


if __name__ == '__main__':
    main()
