matcher:
  KDTreeMatcher:
    knn: 3
    maxDist: 10.0
    epsilon: 0

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.80
  - SurfaceNormalOutlierFilter:
     maxAngle: 1.57

errorMinimizer:
  PointToPlaneErrorMinimizer:

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 100
  - BoundTransformationChecker:
      maxRotationNorm: 0.8
      maxTranslationNorm: 30.00

inspector:
  NullInspector

logger:
  FileLogger
